import { describe, expect, it } from 'vitest';
import { renderLlmsTxt, renderRobotsTxt } from './render.js';
import type { ResolvedPolicy } from './types.js';

const basePolicy: ResolvedPolicy = {
  preset: 'citationFriendly',
  mergeStrategy: 'prepend',
  contentSignals: {},
  rules: [],
  botRules: [],
  sitemaps: []
};

describe('renderRobotsTxt', () => {
  it('includes generator header with preset', () => {
    const result = renderRobotsTxt(basePolicy);
    expect(result).toContain('# Generated by astro-crawler-policy');
    expect(result).toContain('# preset: citationFriendly');
  });

  it('renders default wildcard allow rule when no rules given', () => {
    const result = renderRobotsTxt(basePolicy);
    expect(result).toContain('User-agent: *');
    expect(result).toContain('Allow: /');
  });

  it('renders explicit disallow rule', () => {
    const policy: ResolvedPolicy = {
      ...basePolicy,
      rules: [{ userAgent: ['*'], allow: [], disallow: ['/private/'] }]
    };
    const result = renderRobotsTxt(policy);
    expect(result).toContain('Disallow: /private/');
  });

  it('renders bot disallow rule', () => {
    const policy: ResolvedPolicy = {
      ...basePolicy,
      botRules: [{ id: 'GPTBot', userAgent: 'GPTBot', provider: 'OpenAI', action: 'disallow', categories: ['ai-training'], verified: true }]
    };
    const result = renderRobotsTxt(policy);
    expect(result).toContain('User-agent: GPTBot');
    expect(result).toContain('Disallow: /');
  });

  it('renders bot allow rule', () => {
    const policy: ResolvedPolicy = {
      ...basePolicy,
      botRules: [{ id: 'Googlebot', userAgent: 'Googlebot', provider: 'Google', action: 'allow', categories: ['search'], verified: true }]
    };
    const result = renderRobotsTxt(policy);
    expect(result).toContain('User-agent: Googlebot');
    expect(result).toContain('Allow: /');
  });

  it('renders sitemap entries', () => {
    const policy: ResolvedPolicy = {
      ...basePolicy,
      sitemaps: ['https://example.com/sitemap.xml']
    };
    const result = renderRobotsTxt(policy);
    expect(result).toContain('Sitemap: https://example.com/sitemap.xml');
  });

  it('renders content signals', () => {
    const policy: ResolvedPolicy = {
      ...basePolicy,
      contentSignals: { search: true, aiInput: true, aiTrain: false }
    };
    const result = renderRobotsTxt(policy);
    expect(result).toContain('Content-Signal:');
    expect(result).toContain('search=yes');
    expect(result).toContain('ai-input=yes');
    expect(result).toContain('ai-train=no');
  });

  it('renders host directive', () => {
    const policy: ResolvedPolicy = { ...basePolicy, host: 'example.com' };
    const result = renderRobotsTxt(policy);
    expect(result).toContain('Host: example.com');
  });

  it('host appears before sitemaps', () => {
    const policy: ResolvedPolicy = {
      ...basePolicy,
      host: 'example.com',
      sitemaps: ['https://example.com/sitemap.xml']
    };
    const result = renderRobotsTxt(policy);
    expect(result.indexOf('Host: example.com')).toBeLessThan(result.indexOf('Sitemap:'));
  });

  it('output ends with a newline', () => {
    const result = renderRobotsTxt(basePolicy);
    expect(result.endsWith('\n')).toBe(true);
  });
});

describe('renderLlmsTxt', () => {
  it('uses hostname from site URL as title', () => {
    const result = renderLlmsTxt(basePolicy, 'https://example.com');
    expect(result).toContain('# example.com');
  });

  it('falls back to generic title without site', () => {
    const result = renderLlmsTxt(basePolicy);
    expect(result).toContain('# this site');
  });

  it('includes preset in description', () => {
    const result = renderLlmsTxt(basePolicy, 'https://example.com');
    expect(result).toContain('preset: citationFriendly');
  });

  it('renders content signals in Content Policy section', () => {
    const policy: ResolvedPolicy = {
      ...basePolicy,
      contentSignals: { search: true, aiInput: true, aiTrain: false }
    };
    const result = renderLlmsTxt(policy, 'https://example.com');
    expect(result).toContain('Search indexing: allowed');
    expect(result).toContain('AI citation and summarization: allowed');
    expect(result).toContain('AI training data collection: not allowed');
  });

  it('renders allowed and blocked AI systems', () => {
    const policy: ResolvedPolicy = {
      ...basePolicy,
      botRules: [
        { id: 'Googlebot', userAgent: 'Googlebot', provider: 'Google', action: 'allow', categories: ['search'], verified: true },
        { id: 'GPTBot', userAgent: 'GPTBot', provider: 'OpenAI', action: 'disallow', categories: ['ai-training'], verified: true }
      ]
    };
    const result = renderLlmsTxt(policy);
    expect(result).toContain('### Allowed');
    expect(result).toContain('- Googlebot (Google)');
    expect(result).toContain('### Blocked');
    expect(result).toContain('- GPTBot (OpenAI)');
  });

  it('deduplicates bots with multiple user agents', () => {
    const policy: ResolvedPolicy = {
      ...basePolicy,
      botRules: [
        { id: 'ClaudeBot', userAgent: 'ClaudeBot', provider: 'Anthropic', action: 'allow', categories: ['ai-input'], verified: true },
        { id: 'ClaudeBot', userAgent: 'claude-web', provider: 'Anthropic', action: 'allow', categories: ['ai-input'], verified: true }
      ]
    };
    const result = renderLlmsTxt(policy);
    const count = (result.match(/ClaudeBot/g) ?? []).length;
    expect(count).toBe(1);
  });

  it('renders sitemap entries', () => {
    const policy: ResolvedPolicy = {
      ...basePolicy,
      sitemaps: ['https://example.com/sitemap.xml']
    };
    const result = renderLlmsTxt(policy);
    expect(result).toContain('## Sitemaps');
    expect(result).toContain('- https://example.com/sitemap.xml');
  });

  it('output ends with a newline', () => {
    const result = renderLlmsTxt(basePolicy);
    expect(result.endsWith('\n')).toBe(true);
  });
});
