import type { ContentSignals, ResolvedPolicy, RobotsRule } from './types.js';

export function renderLlmsTxt(policy: ResolvedPolicy, site?: string): string {
  let domain = 'this site';

  if (site) {
    try {
      domain = new URL(site).hostname;
    } catch {
      domain = site;
    }
  }

  const lines: string[] = [];

  lines.push(`# ${domain}`);
  lines.push('');
  lines.push(`> AI content access policy for ${domain}.`);
  lines.push(`> Generated by astro-crawler-policy (preset: ${policy.preset}).`);
  lines.push('');
  lines.push('## Content Policy');
  lines.push('');

  const { search, aiInput, aiTrain } = policy.contentSignals;

  if (search !== undefined) {
    lines.push(`- Search indexing: ${search ? 'allowed' : 'not allowed'}`);
  }

  if (aiInput !== undefined) {
    lines.push(`- AI citation and summarization: ${aiInput ? 'allowed' : 'not allowed'}`);
  }

  if (aiTrain !== undefined) {
    lines.push(`- AI training data collection: ${aiTrain ? 'allowed' : 'not allowed'}`);
  }

  lines.push('');

  const seenIds = new Set<string>();
  const allowedBots: typeof policy.botRules = [];
  const blockedBots: typeof policy.botRules = [];

  for (const bot of policy.botRules) {
    if (seenIds.has(bot.id)) continue;
    seenIds.add(bot.id);
    (bot.action === 'allow' ? allowedBots : blockedBots).push(bot);
  }

  if (allowedBots.length > 0 || blockedBots.length > 0) {
    lines.push('## AI Systems');
    lines.push('');

    if (allowedBots.length > 0) {
      lines.push('### Allowed');
      lines.push('');
      for (const bot of allowedBots) {
        lines.push(`- ${bot.id} (${bot.provider})`);
      }
      lines.push('');
    }

    if (blockedBots.length > 0) {
      lines.push('### Blocked');
      lines.push('');
      for (const bot of blockedBots) {
        lines.push(`- ${bot.id} (${bot.provider})`);
      }
      lines.push('');
    }
  }

  if (policy.sitemaps.length > 0) {
    lines.push('## Sitemaps');
    lines.push('');
    for (const sitemap of policy.sitemaps) {
      lines.push(`- ${sitemap}`);
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}


function renderContentSignals(contentSignals: ContentSignals): string[] {
  const parts: string[] = [];

  if (contentSignals.search !== undefined) {
    parts.push(`search=${contentSignals.search ? 'yes' : 'no'}`);
  }

  if (contentSignals.aiInput !== undefined) {
    parts.push(`ai-input=${contentSignals.aiInput ? 'yes' : 'no'}`);
  }

  if (contentSignals.aiTrain !== undefined) {
    parts.push(`ai-train=${contentSignals.aiTrain ? 'yes' : 'no'}`);
  }

  return parts.length ? [`Content-Signal: ${parts.join(', ')}`] : [];
}

function renderRule(rule: RobotsRule): string[] {
  const lines: string[] = [];

  for (const userAgent of rule.userAgent) {
    lines.push(`User-agent: ${userAgent}`);
  }

  if (rule.comment) {
    lines.push(`# ${rule.comment}`);
  }

  for (const allow of rule.allow ?? []) {
    lines.push(`Allow: ${allow}`);
  }

  for (const disallow of rule.disallow ?? []) {
    lines.push(`Disallow: ${disallow}`);
  }

  if (rule.crawlDelay !== undefined) {
    lines.push(`Crawl-delay: ${rule.crawlDelay}`);
  }

  return lines;
}

export function renderRobotsTxt(policy: ResolvedPolicy): string {
  const lines: string[] = [
    '# Generated by astro-crawler-policy',
    `# preset: ${policy.preset}`,
    ''
  ];

  const wildcardRule =
    policy.rules.find((rule) => rule.userAgent.includes('*')) ?? {
      userAgent: ['*'],
      allow: ['/'],
      disallow: []
    };

  // Render wildcard block with Content-Signal before Allow/Disallow (per spec)
  for (const userAgent of wildcardRule.userAgent) {
    lines.push(`User-agent: ${userAgent}`);
  }
  if (wildcardRule.comment) {
    lines.push(`# ${wildcardRule.comment}`);
  }
  lines.push(...renderContentSignals(policy.contentSignals));
  for (const allow of wildcardRule.allow ?? []) {
    lines.push(`Allow: ${allow}`);
  }
  for (const disallow of wildcardRule.disallow ?? []) {
    lines.push(`Disallow: ${disallow}`);
  }
  if (wildcardRule.crawlDelay !== undefined) {
    lines.push(`Crawl-delay: ${wildcardRule.crawlDelay}`);
  }
  lines.push('');

  for (const rule of policy.rules) {
    if (rule === wildcardRule) {
      continue;
    }

    lines.push(...renderRule(rule));
    lines.push('');
  }

  for (const botRule of policy.botRules) {
    lines.push(`User-agent: ${botRule.userAgent}`);
    lines.push(botRule.action === 'allow' ? 'Allow: /' : 'Disallow: /');
    lines.push('');
  }

  if (policy.host) {
    lines.push(`Host: ${policy.host}`);
  }

  for (const sitemap of policy.sitemaps) {
    lines.push(`Sitemap: ${sitemap}`);
  }

  return `${lines.join('\n').trim()}\n`;
}
